# Generated by Django 2.1.1 on 2018-09-12 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailconfirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirm',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
